---
title: "Untitled"
output: html_document
---

set-up

```{r}

# working directory 
setwd("~/BayesWorkflow/code_r")

# packages
pacman::p_load(tidyverse, 
               brms,
               kableExtra, 
               magick, 
               webshot)

# load functions from fun_helper.R
source("fun_helper.R")

```

load data and ensure correct format.

```{r}

# load data
train <- read_csv("../data/train.csv")

# make sure that data format is okay
train <- train %>%
  mutate(idx = as_factor(idx))

```

load the models

```{r}

# prior fits
m_student_strict_prior <- readRDS("../models_R/m_student_strict_prior.rds")
m_student_reasonable_prior <- readRDS("../models_R/m_student_reasonable_prior.rds")
m_student_vague_prior <- readRDS("../models_R/m_student_vague_prior.rds")

# sampled models
m_student_strict_fit <- readRDS("../models_R/m_student_strict_fit.rds")
m_student_reasonable_fit <- readRDS("../models_R/m_student_reasonable_fit.rds")
m_student_vague_fit <- readRDS("../models_R/m_student_vague_fit.rds")

```


prior predictive checks

```{r}

# strict model 
student_strict_prior_pred <- pp_check(m_student_strict_prior, 
                                     nsamples = 100) +
  labs(title = "R/brms: prior predictive check") 

save_plot(path = "../plots_R/student_strict_prior_pred.png")

# reasonable model
student_reasonable_prior_pred <- pp_check(m_student_reasonable_prior, 
                                         nsamples = 100) + 
  labs(title = "R/brms: prior predictive check")

save_plot(path = "../plots_R/student_reasonable_prior_pred.png")

# vague model
student_vague_prior_pred <- pp_check(m_student_vague_prior, 
                                    nsamples = 100) + 
  labs(title = "R/brms: prior predictive check")

save_plot(path = "../plots_R/student_vague_prior_pred.png")

```

posterior predictive

```{r}

# strict model 
student_strict_posterior_pred <- pp_check(m_student_strict_fit, 
                                         nsamples = 100) + 
  labs(title = "R/brms: posterior predictive check") 

save_plot(path = "../plots_R/student_strict_posterior_pred.png")

# reasonable model
student_reasonable_posterior_pred <- pp_check(m_student_reasonable_fit, 
                                         nsamples = 100) +
  labs(title = "R/brms: posterior predictive check")

save_plot(path = "../plots_R/student_reasonable_posterior_pred.png")

# vague model
student_vague_posterior_pred <- pp_check(m_student_vague_fit, 
                                    nsamples = 100) + 
  labs(title = "R/brms: posterior predictive check")

save_plot(path = "../plots_R/student_vague_posterior_pred.png")

```
