---
title: "Model Comparison (VMP)"
output: html_document
---

set-up

```{r}

# working directory 
setwd("~/BayesWorkflow/code_r")

# packages
pacman::p_load(tidyverse, 
               brms,
               kableExtra, 
               magick, 
               webshot,
               modelr,
               tidybayes)

# load functions from fun_helper.R
source("fun_helper.R")

```

load data 

```{r}

# load data
train <- read_csv("../data/train.csv")

# make sure that data format is okay
train <- train %>%
  mutate(idx = as_factor(idx))

```

load models 

```{r}
# prior fits
m_pooled_prior <- readRDS("../models_R/m_pooled_reasonable_prior.rds")
m_multilevel_prior <- readRDS("../models_R/m_multilevel_reasonable_prior.rds")
m_student_prior <- readRDS("../models_R/m_student_reasonable_prior.rds")

# sampled models
m_pooled_posterior <- readRDS("../models_R/m_pooled_reasonable_fit.rds")
m_multilevel_posterior <- readRDS("../models_R/m_multilevel_reasonable_fit.rds")
m_student_posterior <- readRDS("../models_R/m_student_reasonable_fit.rds")

```

loo comparison (might not go in report). 
but we could try to get it to work with saving..

```{r}

# add criterions 
m_pooled_posterior <- add_criterion(m_pooled_posterior, 
                                    criterion = c("loo", "bayes_R2"))

m_multilevel_posterior <- add_criterion(m_multilevel_posterior, 
                                        criterion = c("loo", "bayes_R2"))

m_student_posterior <- add_criterion(m_student_posterior, 
                                     criterion = c("loo", "bayes_R2"),
                                     moment_match = TRUE) # one problematic observation.

# run loo compare
loo_compare(m_pooled_posterior,
            m_multilevel_posterior,
            m_student_posterior)

# also uses stacking (and gives the same as pyMC3)
loo_model_weights(m_pooled_posterior,
                  m_multilevel_posterior,
                  m_student_posterior)

```

plots for pooled model

```{r}

# testing them. 
prediction_interval_pool(fit = m_pooled_posterior, 
                      title = "Prediction interval (.95, .8) for pooled model",
                      data = train,
                      n_time = 100)

save_plot(path = "../plots_R/pooled_reasonable_PI.png")

fixed_interval_pool(fit = m_pooled_posterior,
                   title = "Fixed effect interval (.95, .8) for pooled model",
                   data = train,
                   n_time = 100)

save_plot(path = "../plots_R/pooled_reasonable_FI.png")

fixed_kruschke_pool(fit = m_pooled_posterior,
                      title = "Fixed effect draws (Kruschke style) for pooled model",
                      data = train,
                      n_time = 100)

save_plot(path = "../plots_R/pooled_reasonable_FK.png")

```

plots for grouped models (multilevel and student-t). 

```{r}

# multilevel
prediction_interval_groups(fit = m_multilevel_posterior, 
                           title = "Prediction interval (.95, .8) for multilevel model",
                           data = train,
                           n_time = 100)

save_plot(path = "../plots_R/multilevel_reasonable_PI.png")

fixed_interval_groups(fit = m_multilevel_posterior,
                      title = "Fixed effect interval (.95, .8) for multilevel model")

save_plot(path = "../plots_R/multilevel_reasonable_FI.png")

# student-t
prediction_interval_groups(fit = m_student_posterior,
                           title = "Prediction interval (.95, .8) for Student-t model")

save_plot(path = "../plots_R/student_reasonable_PI.png")

fixed_interval_groups(fit = m_student_posterior,
                      title = "Fixed effect interval (.95, .8) for Student-t model")

save_plot(path = "../plots_R/student_reasonable_FI.png")

```

MCMC plots of parameters 

```{r}

# pooled 
mcmc_plot(m_pooled_posterior,
          pars = c("b_Intercept",
                   "b_t",
                   "sigma"),
          fixed = T) +
  ggtitle("Posterior intervals (pooled model)")

save_plot(path = "../plots_R/pooled_reasonable_mcmc.png",
          width = 10,
          height = 4)

# multilevel
mcmc_plot(m_multilevel_posterior,
          pars = c("b_Intercept",
                   "b_t",
                   "sigma"),
          fixed = T) +
  ggtitle("Posterior intervals (multilevel model)")

save_plot(path = "../plots_R/multilevel_reasonable_mcmc.png",
          width = 10,
          height = 4)

# student
mcmc_plot(m_student_posterior,
          pars = c("b_Intercept",
                   "b_t",
                   "sigma"),
          fixed = T) +
  ggtitle("Posterior intervals (Student-t model)")

save_plot(path = "../plots_R/student_reasonable_mcmc.png",
          width = 10,
          height = 4)

```

