---
title: "R-Analysis2"
output: html_document
---

```{r}

pacman::p_load(tidyverse, brms)

```

Data: 
Agent based model (from McElreath, but highly modified). 

```{r}

# each year. 
one_year = function(d, 
                    pop = c(1, 2, 3), 
                    popN = c(50, 3, 9),
                    dbeta1 = c(2, 4, 5),
                    dbeta2 = c(6, 2, 5),
                    age_marry = 18, 
                    age_retire = 65){
  
  
  ## people can get married 
  d1 <- d %>%
    mutate(
      lucky = rbinom(n(), 1, happiness/5),
      married = ifelse(married == 0 & age >= age_marry,
                      lucky, married),
      age = age + 1) 
  
  ## old people go to spain 
  d1 <- d1 %>%
    filter(age <= age_retire)
  
  ## new people born 
  birth <- tibble(
    population = rep(pop, popN),
    dbeta_one = rep(dbeta1, popN),
    dbeta_two = rep(dbeta2, popN),
    happiness = rbeta(sum(popN), dbeta_one, dbeta_two),
    age = 0, 
    married = 0,
    lucky = 0)
  
  d2 <- rbind(d1, birth)
  
  return(d2)
  
}

```


```{r}

# set parameters 
pop = c(1, 2, 3)
popN = c(20, 1, 4)
dbeta1 = c(2, 4, 5)
dbeta2 = c(6, 2, 5)
age_marry = 18
age_retire = 65
nsim = 1000

# starting dataframe.
d <- tibble(
  population = rep(pop, popN),
  dbeta_one = rep(dbeta1, popN),
  dbeta_two = rep(dbeta2, popN),
  happiness = rbeta(sum(popN), dbeta_one, dbeta_two),
  age = 0, 
  married = 0,
  lucky = 0)
  
# run a lot of times 
for (i in 1:nsim){
  d <- one_year(d, pop, popN, dbeta1, dbeta2, 
                age_marry, age_retire)
}


```

clean the data

```{r}
# check the data frame
d2 <- d %>%
  mutate(across(c(population, married), ~ as_factor(.x))) %>% #factor
  filter(age >= age_marry) %>% #only adults
  mutate(A = (age-age_marry)/(age_retire-age_marry)) %>% #scale.
  select(-c(dbeta_one, dbeta_two, lucky))

```

check the outcome distribution

```{r}

# thick tails. 
d2 %>% ggplot(aes(x = happiness, fill = population)) + 
  geom_histogram(binwidth = .02)

# check correlation
d2 %>% ggplot(aes(x = age, y = happiness, color = married)) + 
  geom_point() + 
  geom_smooth(method = "lm")

```

model

```{r}

fit_mod <- function(formula,
                    family,
                    data,
                    prior,
                    sample_prior,
                    file){
  
  b <- brm(
  formula = formula,
  family = family,
  data = data,
  prior = prior,
  cores = 4, chains = 2, 
  sample_prior = sample_prior,
  backend = "cmdstanr",
  file = file,
  file_refit = "on_change",
  threads = threading(2),
  control = list(adapt_delta = .99,
                 max_treedepth = 20)
  )
  
  return(b)

}

```

model with normal 

```{r}

## just fit directly. 
m0 <- fit_mod(
  data = d2,
  formula = bf(happiness ~ 1 + A),
  family = gaussian, 
  prior = c(
    prior(normal(0.5, 0.2), class = Intercept),
    prior(normal(0, 0.2), class = b),
    prior(exponential(1), class = sigma)
  ),
  sample_prior = T,
  file = "../models/m0"
)

## check the model
pp_check(m0)

```

model this without multilevel (student t). 

```{r}

## just fit directly. 
m1 <- fit_mod(
  data = d2,
  formula = bf(happiness ~ 1 + A),
  family = student, 
  prior = c(
    prior(normal(0.5, 0.2), class = Intercept),
    prior(normal(0, 0.2), class = b),
    prior(exponential(1), class = sigma),
    prior(gamma(2, 0.1), class = nu)
  ),
  sample_prior = T,
  file = "../models/m1"
)

## check the model
pp_check(m1)

```

lognormal?

```{r}

# of course the priors here make no sense. 
m2 <- fit_mod(
  data = d2,
  formula = bf(happiness ~ 1 + A),
  family = lognormal, 
  prior = c(
    prior(normal(0.5, 0.2), class = Intercept),
    prior(normal(0, 0.2), class = b),
    prior(exponential(1), class = sigma)
  ),
  sample_prior = T,
  file = "../models/m2"
)

pp_check(m2, nsamples = 50)
pp_check(m1, nsamples = 50)
pp_check(m0, nsamples = 50)

```

gamma:
now we just have the issue of actually using this for something..

```{r}
get_prior(data = d2, formula = bf(happiness ~ 1 + A), family = Gamma(link = "log"))

m3 <- fit_mod(
  data = d2, 
  formula = bf(happiness ~ 1 + A),
  family = Gamma(link = "log"),
  prior = c(
    prior(normal(0.5, 0.2), class = Intercept),
    prior(normal(0, 0.2), class = b),
    prior(gamma(0.01, 0.01), class = shape)
  ),
  sample_prior = T,
  file = "../models/m3")

pp_check(m3, nsamples = 50)

```

