---
title: "Untitled"
output: html_document
---

set-up

```{r}

# working directory 
setwd("~/BayesWorkflow/code_r")

# packages
pacman::p_load(tidyverse, 
               brms,
               modelr,
               tidybayes,
               bayesplot)

# load functions from fun_models.R
source("fun_models.R")
source("fun_helper.R")

```

global arguments

```{r}

# Only this is flexible at the moment. Not as nice as the python setup. 
n_pp = 100

```

load data and ensure correct format.

```{r}

# load data
train <- read_csv("../data/train.csv") %>%
  mutate(idx = as_factor(idx))

```

specify formula. 

```{r}

#formula 
f_multilevel <- bf(y ~ 1 + t + (1+t|idx)) # random eff. structure

```

Get priors and set priors. 

```{r}

# fit the first model
get_prior(formula = f_multilevel,
          data = train,
          family = gaussian,
          
)

# set priors: three levels.
prior_multilevel_specific <- c(
  prior(normal(0, 0.05), class = b),
  prior(normal(1.5, 0.05), class = Intercept),
  prior(normal(0, 0.05), class = sd),
  prior(normal(0, 0.05), class = sigma),
  prior(lkj(1), class = cor)
)

prior_multilevel_generic <- c(
  prior(normal(0, 0.5), class = b),
  prior(normal(1.5, 0.5), class = Intercept),
  prior(normal(0, 0.5), class = sd),
  prior(normal(0, 0.5), class = sigma),
  prior(lkj(1), class = cor)
)

prior_multilevel_weak <- c(
  prior(normal(0, 5), class = b),
  prior(normal(1.5, 5), class = Intercept),
  prior(normal(0, 5), class = sd),
  prior(normal(0, 5), class = sigma),
  prior(lkj(1), class = cor)
)

```

Now we compile models and check prior predictive.

```{r}

# compile the models
m_multilevel_specific_prior <- fit_mod(
  formula = f_multilevel,
  family = gaussian,
  data = train,
  prior = prior_multilevel_specific,
  sample_prior = "only",
  file = "../models_R/m_multilevel_specific_prior"
)

m_multilevel_generic_prior <- fit_mod(
  formula = f_multilevel,
  family = gaussian,
  data = train,
  prior = prior_multilevel_generic,
  sample_prior = "only",
  file = "../models_R/m_multilevel_generic_prior"
)

m_multilevel_weak_prior <- fit_mod(
  formula = f_multilevel,
  family = gaussian,
  data = train,
  prior = prior_multilevel_weak,
  sample_prior = "only",
  file = "../models_R/m_multilevel_weak_prior"
)

```

check the prior predictive checks

```{r}

# specific model 
multilevel_specific_prior_pred <- pp_check(m_multilevel_specific_prior, 
                                     nsamples = 100) +
  labs(title = "R/brms: prior predictive check") 

save_plot(path = "../plots_R/multilevel_specific_prior_pred.png")

# generic model
multilevel_generic_prior_pred <- pp_check(m_multilevel_generic_prior, 
                                         nsamples = 100) + 
  labs(title = "R/brms: prior predictive check")

save_plot(path = "../plots_R/multilevel_generic_prior_pred.png")

# weak model
multilevel_weak_prior_pred <- pp_check(m_multilevel_weak_prior, 
                                    nsamples = 100) + 
  labs(title = "R/brms: prior predictive check")

save_plot(path = "../plots_R/multilevel_weak_prior_pred.png")

```

fit the models 

```{r}

# fit the models
m_multilevel_specific_fit <- fit_mod(
  formula = f_multilevel,
  family = gaussian,
  data = train,
  prior = prior_multilevel_specific,
  sample_prior = TRUE,
  file = "../models_R/m_multilevel_specific_fit"
)

m_multilevel_generic_fit <- fit_mod(
  formula = f_multilevel,
  family = gaussian,
  data = train,
  prior = prior_multilevel_generic,
  sample_prior = TRUE,
  file = "../models_R/m_multilevel_generic_fit"
)

m_multilevel_weak_fit <- fit_mod(
  formula = f_multilevel,
  family = gaussian,
  data = train,
  prior = prior_multilevel_weak,
  sample_prior = TRUE,
  file = "../models_R/m_multilevel_weak_fit"
)

```

plot trace

```{r}

# specific model
save_chains(
  fit = m_multilevel_specific_fit,
  path = "../plots_R/multilevel_specific_plot_trace.png"
)

# generic model
save_chains(
  fit = m_multilevel_generic_fit,
  path = "../plots_R/multilevel_generic_plot_trace.png"
)

# weak model
save_chains(
  fit = m_multilevel_weak_fit,
  path = "../plots_R/multilevel_weak_plot_trace.png"
)

```

posterior predictive checks 

```{r}

# specific model 
multilevel_specific_posterior_pred <- pp_check(m_multilevel_specific_fit, 
                                         nsamples = 100) + 
  labs(title = "R/brms: posterior predictive check") 

save_plot(path = "../plots_R/multilevel_specific_posterior_pred.png")

# generic model
multilevel_generic_posterior_pred <- pp_check(m_multilevel_generic_fit, 
                                         nsamples = 100) +
  labs(title = "R/brms: posterior predictive check")

save_plot(path = "../plots_R/multilevel_generic_posterior_pred.png")

# weak model
multilevel_weak_posterior_pred <- pp_check(m_multilevel_weak_fit, 
                                    nsamples = 100) + 
  labs(title = "R/brms: posterior predictive check")

save_plot(path = "../plots_R/multilevel_weak_posterior_pred.png")

```

### HDI vs data ### 

fixed effects HDI vs. data

```{r}

# specific
fixed_interval_groups(fit = m_multilevel_specific_fit,
                    title = "Fixed effect interval (.95, .8)",
                    data = train,
                    n_time = 100)

save_plot(path = "../plots_R/multilevel_specific_HDI_fixed.png")

# generic
fixed_interval_groups(fit = m_multilevel_generic_fit,
                    title = "Fixed effect interval (.95, .8)",
                    data = train,
                    n_time = 100)

save_plot(path = "../plots_R/multilevel_generic_HDI_fixed.png")

# weak
fixed_interval_groups(fit = m_multilevel_weak_fit,
                    title = "Fixed effect interval (.95, .8)",
                    data = train,
                    n_time = 100)

save_plot(path = "../plots_R/multilevel_weak_HDI_fixed.png")

```

prediction intervals

```{r}

# specific
prediction_interval_groups(fit = m_multilevel_specific_fit, 
                           title = "Prediction interval (.95, .8)",
                           data = train,
                           n_time = 100)

save_plot(path = "../plots_R/multilevel_specific_HDI_full.png")

# generic
prediction_interval_groups(fit = m_multilevel_generic_fit, 
                           title = "Prediction interval (.95, .8)",
                           data = train,
                           n_time = 100)

save_plot(path = "../plots_R/multilevel_generic_HDI_full.png")

# weak
prediction_interval_groups(fit = m_multilevel_weak_fit, 
                           title = "Prediction interval (.95, .8)",
                           data = train,
                           n_time = 100)

save_plot(path = "../plots_R/multilevel_weak_HDI_full.png")

```

### MCMC (hdi for parameters) ###
uses the bayesplot package. 

```{r}

# for consistency with python. 
# does not do anything at the moment..
width = 7
height = 4

# specific
mcmc_hdi(fit = m_multilevel_specific_fit, 
         title = "R/brms: HDI intervals for parameters")

save_plot(path = "../plots_R/multilevel_specific_HDI_param.png",
          width = width,
          height = height)

# generic
mcmc_hdi(fit = m_multilevel_generic_fit, 
         title = "R/brms: HDI intervals for parameters")

save_plot(path = "../plots_R/multilevel_generic_HDI_param.png",
          width = width,
          height = height)

# weak
mcmc_hdi(fit = m_multilevel_weak_fit, 
         title = "R/brms: HDI intervals for parameters")

save_plot(path = "../plots_R/multilevel_weak_HDI_param.png",
          width = width,
          height = height)

```


