---
title: "Untitled"
output: html_document
---

set-up

```{r}

# working directory 
setwd("~/BayesWorkflow/code_r")

# packages
pacman::p_load(tidyverse, 
               brms)

# load functions from fun_models.R
source("fun_models.R")

```

load data and ensure correct format.

```{r}

# load data
train <- read_csv("../data/train.csv")

# make sure that data format is okay
train <- train %>%
  mutate(idx = as_factor(idx))

```

specify formula. 

```{r}

#formula 
f_student <- bf(y ~ 1 + t + (1+t|idx)) # complete pooling 

```

Get priors and set priors. 

```{r}

# fit the first model
get_prior(formula = f_student,
          data = train,
          family = student,
          
)

# set priors: three levels.
prior_student_strict <- c(
  prior(normal(0, 0.05), class = b),
  prior(normal(1.5, 0.05), class = Intercept),
  prior(normal(0, 0.05), class = sd),
  prior(normal(0, 0.05), class = sigma),
  prior(lkj(1), class = cor),
  prior(gamma(2, 0.1), class = nu) # same as in python. 
)

prior_student_reasonable <- c(
  prior(normal(0, 0.5), class = b),
  prior(normal(1.5, 0.5), class = Intercept),
  prior(normal(0, 0.5), class = sd),
  prior(normal(0, 0.5), class = sigma),
  prior(lkj(1), class = cor),
  prior(gamma(2, 0.1), class = nu)
)

prior_student_vague <- c(
  prior(normal(0, 5), class = b),
  prior(normal(1.5, 5), class = Intercept),
  prior(normal(0, 5), class = sd),
  prior(normal(0, 5), class = sigma),
  prior(lkj(1), class = cor),
  prior(gamma(2, 0.1), class = nu)
)

```

Now we compile models and check prior predictive.

```{r}

# compile the models
m_student_strict_prior <- fit_mod(
  formula = f_student,
  family = student,
  data = train,
  prior = prior_student_strict,
  sample_prior = "only",
  file = "../models_R/m_student_strict_prior"
)

m_student_reasonable_prior <- fit_mod(
  formula = f_student,
  family = student,
  data = train,
  prior = prior_student_reasonable,
  sample_prior = "only",
  file = "../models_R/m_student_reasonable_prior"
)

m_student_vague_prior <- fit_mod(
  formula = f_student,
  family = student,
  data = train,
  prior = prior_student_vague,
  sample_prior = "only",
  file = "../models_R/m_student_vague_prior"
)

```

check the prior predictive checks

```{r}

pp_check(m_student_strict_prior, nsamples = 100)
pp_check(m_student_reasonable_prior, nsamples = 100)
pp_check(m_student_vague_prior, nsamples = 100)

```

fit the models 

```{r}

# fit the models
m_student_strict_fit <- fit_mod(
  formula = f_student,
  family = student,
  data = train,
  prior = prior_student_strict,
  sample_prior = TRUE,
  file = "../models_R/m_student_strict_fit"
)

m_student_reasonable_fit <- fit_mod(
  formula = f_student,
  family = student,
  data = train,
  prior = prior_student_reasonable,
  sample_prior = TRUE,
  file = "../models_R/m_student_reasonable_fit"
)

m_student_vague_fit <- fit_mod(
  formula = f_student,
  family = student,
  data = train,
  prior = prior_student_vague,
  sample_prior = TRUE,
  file = "../models_R/m_student_vague_fit"
)

```

posterior predictive checks 

```{r}

pp_check(m_student_strict_fit, nsamples = 100)
pp_check(m_student_reasonable_fit, nsamples = 100)
pp_check(m_student_vague_fit, nsamples = 100)

```
