---
title: "Untitled"
output: html_document
---

set-up

```{r}
# packages
pacman::p_load(tidyverse, 
               brms,
               modelr,
               tidybayes,
               bayesplot)
source("fun_helper.R")
```

generate data (not saved)

```{r}
### R: simulate data ###
set.seed(42)
d <- tibble(idx = seq(0, 14),
            t = seq(0, 14)) %>%
  data_grid(idx, t) %>%
  group_by(idx) %>%
  mutate(a_real = rnorm(1, 1, 0.5),
         b_real = rnorm(1, 0.3, 0.2),
         eps_real = rnorm(15, 0, 0.5),
         y = a_real + b_real * t + eps_real) %>%
  select(c(idx, t, y)) %>%
  mutate(idx = as_factor(idx))
  
# split into test & train
train <- d %>%
  filter(t <= 9)
test <- d %>%
  filter(t > 9)
# save data (we use python data in the app)
write_csv(train, "../data/train_R.csv")
write_csv(test, "../data/test_R.csv")
```

read data from python simulation

```{r}
# read train data
train <- read_csv("../data/train.csv") %>%
  mutate(idx = as_factor(idx))
```

```{r}
# quick EDA
ggplot(data = train, aes(x = t, y = y, color = idx)) +
  geom_point() + 
  geom_smooth(method = "lm", aes(fill = idx), alpha = 0.2) + 
  ggtitle("R: Quick EDA")
# save 
save_plot(
  path = "../plots_R/EDA.png"
)
```