---
title: "Untitled"
output: html_document
---

set-up

```{r}
# packages
pacman::p_load(tidyverse, 
               brms,
               modelr,
               tidybayes,
               bayesplot)
RANDOM_SEED = 42
# load functions from fun_models.R
source("fun_models.R")
source("fun_helper.R")
```

global arguments

```{r}
# Only this is flexible at the moment. Not as nice as the python setup. 
n_pp = 100
```


load data and ensure correct format.

```{r}
# load data
train <- read_csv("../data/train.csv") %>%
  mutate(idx = as_factor(idx))
```

specify formula. 

```{r}
#formula 
f_pooled <- bf(y ~ 0 + Intercept + t) # complete pooling 
```

Get priors and set priors. 

```{r}
# fit the first model
get_prior(formula = f_pooled,
          data = train,
          family = gaussian,
          
)
# set priors: three levels.
prior_pooled_specific <- c(
  prior(normal(0, 0.05), class = b, coef = t),
  prior(normal(1.5, 0.05), class = b, coef = Intercept),
  prior(normal(0, 0.05), class = sigma)
)
prior_pooled_generic <- c(
  prior(normal(0, 0.5), class = b, coef = t),
  prior(normal(1.5, 0.5), class = b, coef = Intercept),
  prior(normal(0, 0.5), class = sigma)
)
prior_pooled_weak <- c(
  prior(normal(0, 5), class = b, coef = t),
  prior(normal(1.5, 5), class = b, coef = Intercept),
  prior(normal(0, 5), class = sigma)
)
```

Now we compile models and check prior predictive.

```{r}
# compile the models
m_pooled_specific_prior <- fit_mod(
  formula = f_pooled,
  family = gaussian,
  data = train,
  prior = prior_pooled_specific,
  sample_prior = "only",
  file = "../models_R/m_pooled_specific_prior",
  random_seed = RANDOM_SEED
)
m_pooled_generic_prior <- fit_mod(
  formula = f_pooled,
  family = gaussian,
  data = train,
  prior = prior_pooled_generic,
  sample_prior = "only",
  file = "../models_R/m_pooled_generic_prior",
  random_seed = RANDOM_SEED
)
m_pooled_weak_prior <- fit_mod(
  formula = f_pooled,
  family = gaussian,
  data = train,
  prior = prior_pooled_weak,
  sample_prior = "only",
  file = "../models_R/m_pooled_weak_prior",
  random_seed = RANDOM_SEED
)
```

check the prior predictive checks

```{r}
# specific model 
pooled_specific_prior_pred <- pp_check(m_pooled_specific_prior, 
                                     nsamples = 100) +
  labs(title = "R/brms: prior predictive check") 
save_plot(path = "../plots_R/pooled_specific_prior_pred.png")
# generic model
pooled_generic_prior_pred <- pp_check(m_pooled_generic_prior, 
                                         nsamples = 100) + 
  labs(title = "R/brms: prior predictive check")
save_plot(path = "../plots_R/pooled_generic_prior_pred.png")
# weak model
pooled_weak_prior_pred <- pp_check(m_pooled_weak_prior, 
                                    nsamples = 100) + 
  labs(title = "R/brms: prior predictive check")
save_plot(path = "../plots_R/pooled_weak_prior_pred.png")
```

fit the models 

```{r}
# fit the models
m_pooled_specific_fit <- fit_mod(
  formula = f_pooled,
  family = gaussian,
  data = train,
  prior = prior_pooled_specific,
  sample_prior = TRUE,
  file = "../models_R/m_pooled_specific_fit",
  random_seed = RANDOM_SEED
)
m_pooled_generic_fit <- fit_mod(
  formula = f_pooled,
  family = gaussian,
  data = train,
  prior = prior_pooled_generic,
  sample_prior = TRUE,
  file = "../models_R/m_pooled_generic_fit",
  random_seed = RANDOM_SEED
)
m_pooled_weak_fit <- fit_mod(
  formula = f_pooled,
  family = gaussian,
  data = train,
  prior = prior_pooled_weak,
  sample_prior = TRUE,
  file = "../models_R/m_pooled_weak_fit",
  random_seed = RANDOM_SEED
)
```

plot trace

```{r}
# specific model
save_chains(
  fit = m_pooled_specific_fit,
  path = "../plots_R/pooled_specific_plot_trace.png"
)
# generic model
save_chains(
  fit = m_pooled_generic_fit,
  path = "../plots_R/pooled_generic_plot_trace.png"
)
# weak model
save_chains(
  fit = m_pooled_weak_fit,
  path = "../plots_R/pooled_weak_plot_trace.png"
)
```

posterior predictive checks 

```{r}
# specific model 
pooled_specific_posterior_pred <- pp_check(m_pooled_specific_fit, 
                                         nsamples = 100) + 
  labs(title = "R/brms: posterior predictive check") 
save_plot(path = "../plots_R/pooled_specific_posterior_pred.png")
# generic model
pooled_generic_posterior_pred <- pp_check(m_pooled_generic_fit, 
                                         nsamples = 100) +
  labs(title = "R/brms: posterior predictive check")
save_plot(path = "../plots_R/pooled_generic_posterior_pred.png")
# weak model
pooled_weak_posterior_pred <- pp_check(m_pooled_weak_fit, 
                                    nsamples = 100) + 
  labs(title = "R/brms: posterior predictive check")
save_plot(path = "../plots_R/pooled_weak_posterior_pred.png")
```

### HDI vs data ### 

fixed effects HDI vs. data

```{r}
# specific
fixed_interval_pool(fit = m_pooled_specific_fit,
                    title = "R/brms: Prediction intervals (fixed)",
                    data = train,
                    n_time = 100)
save_plot(path = "../plots_R/pooled_specific_HDI_fixed.png")
# generic
fixed_interval_pool(fit = m_pooled_generic_fit,
                    title = "R/brms: Prediction intervals (fixed)",
                    data = train,
                    n_time = 100)
save_plot(path = "../plots_R/pooled_generic_HDI_fixed.png")
# weak
fixed_interval_pool(fit = m_pooled_weak_fit,
                    title = "R/brms: Prediction intervals (fixed)",
                    data = train,
                    n_time = 100)
save_plot(path = "../plots_R/pooled_weak_HDI_fixed.png")
```

fixed kruschke style 

```{r}
# specific
fixed_kruschke_pool(fit = m_pooled_specific_fit,
                      title = "R/brms: Fixed effect draws (Kruschke style)",
                      data = train,
                      n_time = 100)
save_plot(path = "../plots_R/pooled_specific_HDI_kruschke.png")
# generic
fixed_kruschke_pool(fit = m_pooled_generic_fit,
                      title = "R/brms: Fixed effect draws (Kruschke style)",
                      data = train,
                      n_time = 100)
save_plot(path = "../plots_R/pooled_generic_HDI_kruschke.png")
# weak
fixed_kruschke_pool(fit = m_pooled_weak_fit,
                      title = "R/brms: Fixed effect draws (Kruschke style)",
                      data = train,
                      n_time = 100)
save_plot(path = "../plots_R/pooled_weak_HDI_kruschke.png")
```

prediction intervals

```{r}
# specific
prediction_interval_pool(fit = m_pooled_specific_fit, 
                         title = "R/brms: Prediction intervals (full)",
                         data = train,
                         n_time = 100)
save_plot(path = "../plots_R/pooled_specific_HDI_full.png")
# generic
prediction_interval_pool(fit = m_pooled_generic_fit, 
                         title = "R/brms: Prediction intervals (full)",
                         data = train,
                         n_time = 100)
save_plot(path = "../plots_R/pooled_generic_HDI_full.png")
# weak
prediction_interval_pool(fit = m_pooled_weak_fit, 
                         title = "R/brms: Prediction intervals (full)",
                         data = train,
                         n_time = 100)
save_plot(path = "../plots_R/pooled_weak_HDI_full.png")
```

### MCMC (hdi for parameters) ###

```{r}
# for consistency with python. 
width = 7
height = 4
# specific
mcmc_hdi(fit = m_pooled_specific_fit, 
         title = "R/brms: HDI intervals for parameters")
save_plot(path = "../plots_R/pooled_specific_HDI_param.png",
          width = width,
          height = height)
# generic
mcmc_hdi(fit = m_pooled_generic_fit, 
         title = "R/brms: HDI intervals for parameters")
save_plot(path = "../plots_R/pooled_generic_HDI_param.png",
          width = width,
          height = height)
# weak
mcmc_hdi(fit = m_pooled_weak_fit, 
         title = "R/brms: HDI intervals for parameters")
save_plot(path = "../plots_R/pooled_weak_HDI_param.png",
          width = width,
          height = height)
```
