# https://share.streamlit.io/streamlit/theming-showcase-blue/main
[theme]
primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#C6CDD4"
font = "sans serif"
